version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: "${APP_NAME}_REDIS"
    networks:
      - webhook-git
    volumes:
     - $PWD/redis:/var/lib/redis

  app:
    build:
      context: .
      dockerfile: docker-config/Dockerfile
    restart: always
    container_name: "${APP_NAME}_APP"
    image: webhook-image
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis
    networks:
      - webhook-git

  job:
    image: webhook-image
    restart: always
    container_name: "${APP_NAME}_JOB"
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      DOCKER_APP: job
    depends_on:
      - redis
    networks:
      - webhook-git

networks:
  webhook-git: