version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: "${APP_NAME}_REDIS"
    networks:
      - generate-report-webhook
    volumes:
     - $PWD/redis:/var/lib/redis

  app:
    build:
      context: .
      dockerfile: docker-config/Dockerfile
    restart: always
    container_name: "${APP_NAME}_APP"
    image: generate-report-webhook
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis
    networks:
      - generate-report-webhook

networks:
  generate-report-webhook: